# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_instance_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormInstanceFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('flow_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.Field')),
                ('form_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.FormTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hebrew_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='forminstancefieldvalue',
            name='form_field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.FormTemplateField'),
        ),
        migrations.AddField(
            model_name='forminstancefieldvalue',
            name='form_instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.FormInstance'),
        ),
        migrations.AddField(
            model_name='forminstance',
            name='form_template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.FormTemplate'),
        ),
        migrations.AddField(
            model_name='forminstance',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.User'),
        ),
        migrations.AddField(
            model_name='field',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsApp.IdType'),
        ),
    ]
